# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:

    pre_build:
      - ./docs/pre_install.sh
      - cd docs && mkdir -p build && doxygen Doxyfile
      - cd docs && plot.py plotdefs.json images/

  apt_packages:
    - graphviz

conda:
  environment: docs/plot/environment.yml

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt

formats: all
