name: proj
channels:
  - conda-forge
dependencies:
  - libcurl
  - libcxx
  - libsqlite
  - libtiff
  - sqlite
  - compilers
  - cmake
  - ninja
  - pip:
    - breathe
    - pybtex
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
    - sphinxcontrib-spelling
